management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  security:
    user:
      name: yul
      password: 123456
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true